### ISSUE TITLE
New Points system

### ISSUE THREAD

**Issue by earmstrong1990** [KandyMan1990/GreenRoomPlinko#27]
Instead of the current percentage based system, which doesn't take into account the amount of players in a game, a new system has been proposed.

The winner of a game should be awarded the amount of people in the game -1 in points, while the losers of a game should be awarded -1 points.  The idea being that there's no such thing as a "risky" game points wise, as on average, you should balance out to 0 points, eg 10 games of 10 people, you should lose 1 out of those 10.  1 time you gain 9 points, the other 9 times you lose 1 point.

**Comment by KandyMan1990** [comment]
New points system completed and merged
