### ISSUE TITLE
I am too blind to tell who's ball belongs to who

### ISSUE THREAD

**Issue by IanMcLeodTombola** [KandyMan1990/GreenRoomPlinko#5]
Could we have the colour appear next to their name on the HUD, or could we have images of some kind?

**Comment by kevinainleywalker** [comment]
Perhaps if the colours were a little brighter, and a little less well designed.

Like bingo80

**Comment by earmstrong1990** [comment]
I'll make the colours even more brighterer again, and if it'll help I'll pick colours from a pool instead of random as some are very similar

**Comment by IanMcLeodTombola** [comment]
It's not to do with the brightness. I can see what colours are what just fine. 
It's that I can't read the small text on the ball. I don't think anything could be done about that 
I think it would be easier if the colours were assigned on the HUD too where the text is bigger

**Comment by kevinainleywalker** [comment]
Our avatars in the tiny balls?
